name: Wechat Android Dest Version

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
    
jobs:
  check_wechat_android_new_version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Validate version data
        run: node scripts/validate.js
      - name: Check new version and push
        env:
          GH_TOKEN: ${{ github.token }}
        run: bash ./scripts/updateVersion.sh
      - name: Validate version data after update
        run: node scripts/validate.js
          